[[headers]]
  for = "/fonts/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/data/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"

[[redirects]]
  from = "/tamapark-api/*"
  to = "http://tamapark.gs.keitaiarchive.org/:splat"
  status = 200